### ISSUE TITLE
Set up a project repository

### ISSUE THREAD

**Issue by khaled-rashwan** [Njaz-org/Estebian#5]
Choose VCS, create repository, configure settings

### Subtasks

- [x] Choose a Version Control System
- [x] Create a Repository
- [x] Initialize the Repository with a README
- [x] Add a .gitignore File
- [x] Set Up Branch Protection Rules
- [ ] Invite Collaborators (if any)
